import "./globals.css";
import UseAOS from "@/components/utilities/aos";
import { UseLenis } from "@/components/utilities/lenis";
import { sans } from "@/lib/fonts";
import Footer from "@/components/sections/footer";
import Navbar from "@/components/navbar/navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${sans.variable} font-sans antialiased`}
      >
        <Navbar />
        <UseAOS />
        <UseLenis />
        {children}
        <Footer />
      </body>
    </html>
  );
}